# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo_calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(589, 497)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditFirstNumber = QtWidgets.QLineEdit(Dialog)
        self.lineEditFirstNumber.setObjectName("lineEditFirstNumber")
        self.gridLayout.addWidget(self.lineEditFirstNumber, 0, 2, 1, 1)
        self.lineEditSecondNumber = QtWidgets.QLineEdit(Dialog)
        self.lineEditSecondNumber.setObjectName("lineEditSecondNumber")
        self.gridLayout.addWidget(self.lineEditSecondNumber, 1, 2, 1, 1)
        self.labelFirstNumber = QtWidgets.QLabel(Dialog)
        self.labelFirstNumber.setObjectName("labelFirstNumber")
        self.gridLayout.addWidget(self.labelFirstNumber, 0, 0, 1, 2)
        self.labelSecondNumber = QtWidgets.QLabel(Dialog)
        self.labelSecondNumber.setObjectName("labelSecondNumber")
        self.gridLayout.addWidget(self.labelSecondNumber, 1, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonPlus = QtWidgets.QPushButton(Dialog)
        self.pushButtonPlus.setObjectName("pushButtonPlus")
        self.horizontalLayout.addWidget(self.pushButtonPlus)
        self.pushButtonSubtract = QtWidgets.QPushButton(Dialog)
        self.pushButtonSubtract.setObjectName("pushButtonSubtract")
        self.horizontalLayout.addWidget(self.pushButtonSubtract)
        self.pushButtonMultiply = QtWidgets.QPushButton(Dialog)
        self.pushButtonMultiply.setObjectName("pushButtonMultiply")
        self.horizontalLayout.addWidget(self.pushButtonMultiply)
        self.pushButtonDivide = QtWidgets.QPushButton(Dialog)
        self.pushButtonDivide.setObjectName("pushButtonDivide")
        self.horizontalLayout.addWidget(self.pushButtonDivide)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.labelResult = QtWidgets.QLabel(Dialog)
        self.labelResult.setText("")
        self.labelResult.setObjectName("labelResult")
        self.verticalLayout.addWidget(self.labelResult)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelFirstNumber.setText(_translate("Dialog", "First Number"))
        self.labelSecondNumber.setText(_translate("Dialog", "Second Number"))
        self.pushButtonPlus.setText(_translate("Dialog", "+"))
        self.pushButtonSubtract.setText(_translate("Dialog", "-"))
        self.pushButtonMultiply.setText(_translate("Dialog", "*"))
        self.pushButtonDivide.setText(_translate("Dialog", "/"))
