# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_pane.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(474, 424)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setMinimumSize(QtCore.QSize(450, 400))
        self.widget.setMaximumSize(QtCore.QSize(450, 400))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.account_le = QtWidgets.QLineEdit(self.widget)
        self.account_le.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.account_le.setFont(font)
        self.account_le.setObjectName("account_le")
        self.gridLayout.addWidget(self.account_le, 0, 0, 1, 2)
        self.password_le = QtWidgets.QLineEdit(self.widget)
        self.password_le.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.password_le.setFont(font)
        self.password_le.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.password_le.setObjectName("password_le")
        self.gridLayout.addWidget(self.password_le, 1, 0, 1, 2)
        self.refres_btn = QtWidgets.QPushButton(self.widget)
        self.refres_btn.setMinimumSize(QtCore.QSize(60, 60))
        self.refres_btn.setMaximumSize(QtCore.QSize(60, 60))
        self.refres_btn.setObjectName("refres_btn")
        self.gridLayout.addWidget(self.refres_btn, 2, 0, 1, 1)
        self.captcha_label = MyLabel(self.widget)
        self.captcha_label.setMinimumSize(QtCore.QSize(293, 190))
        self.captcha_label.setMaximumSize(QtCore.QSize(293, 190))
        self.captcha_label.setStyleSheet("background-color: rgb(153, 102, 51);")
        self.captcha_label.setObjectName("captcha_label")
        self.gridLayout.addWidget(self.captcha_label, 2, 1, 2, 1)
        self.auto_captcha_btn = QtWidgets.QPushButton(self.widget)
        self.auto_captcha_btn.setMinimumSize(QtCore.QSize(60, 60))
        self.auto_captcha_btn.setMaximumSize(QtCore.QSize(60, 60))
        self.auto_captcha_btn.setObjectName("auto_captcha_btn")
        self.gridLayout.addWidget(self.auto_captcha_btn, 3, 0, 1, 1)
        self.login_btn = QtWidgets.QPushButton(self.widget)
        self.login_btn.setMinimumSize(QtCore.QSize(0, 50))
        self.login_btn.setObjectName("login_btn")
        self.gridLayout.addWidget(self.login_btn, 4, 0, 1, 2)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        self.refres_btn.clicked.connect(Form._slot_refresh_captcha)
        self.auto_captcha_btn.clicked.connect(Form._slot_auto_captcha)
        self.login_btn.clicked.connect(Form._slot_login_check)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.account_le.setPlaceholderText(_translate("Form", "请输入12306账户"))
        self.password_le.setPlaceholderText(_translate("Form", "请输入12306密码"))
        self.refres_btn.setText(_translate("Form", "刷新"))
        self.captcha_label.setText(_translate("Form", "TextLabel"))
        self.auto_captcha_btn.setText(_translate("Form", "打码"))
        self.login_btn.setText(_translate("Form", "登录"))
from my_label import MyLabel


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
