# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoCheckbox2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(566, 517)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(240, 10, 60, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(90, 50, 141, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(90, 210, 111, 16))
        self.label_3.setObjectName("label_3")
        self.labelAmount = QtWidgets.QLabel(Dialog)
        self.labelAmount.setGeometry(QtCore.QRect(50, 360, 461, 20))
        self.labelAmount.setText("")
        self.labelAmount.setObjectName("labelAmount")
        self.groupBoxIceCreams = QtWidgets.QGroupBox(Dialog)
        self.groupBoxIceCreams.setGeometry(QtCore.QRect(260, 30, 241, 141))
        self.groupBoxIceCreams.setCheckable(True)
        self.groupBoxIceCreams.setObjectName("groupBoxIceCreams")
        self.checkBoxRockyRoad = QtWidgets.QCheckBox(self.groupBoxIceCreams)
        self.checkBoxRockyRoad.setGeometry(QtCore.QRect(20, 110, 211, 20))
        self.checkBoxRockyRoad.setObjectName("checkBoxRockyRoad")
        self.checkBoxChoclateChips = QtWidgets.QCheckBox(self.groupBoxIceCreams)
        self.checkBoxChoclateChips.setGeometry(QtCore.QRect(20, 20, 171, 20))
        self.checkBoxChoclateChips.setObjectName("checkBoxChoclateChips")
        self.checkBoxCookieDough = QtWidgets.QCheckBox(self.groupBoxIceCreams)
        self.checkBoxCookieDough.setGeometry(QtCore.QRect(20, 50, 191, 20))
        self.checkBoxCookieDough.setObjectName("checkBoxCookieDough")
        self.checkBoxChoclateAlmond = QtWidgets.QCheckBox(self.groupBoxIceCreams)
        self.checkBoxChoclateAlmond.setGeometry(QtCore.QRect(20, 80, 211, 20))
        self.checkBoxChoclateAlmond.setObjectName("checkBoxChoclateAlmond")
        self.groupBoxDrinks = QtWidgets.QGroupBox(Dialog)
        self.groupBoxDrinks.setGeometry(QtCore.QRect(260, 190, 201, 121))
        self.groupBoxDrinks.setCheckable(True)
        self.groupBoxDrinks.setObjectName("groupBoxDrinks")
        self.checkBoxSoda = QtWidgets.QCheckBox(self.groupBoxDrinks)
        self.checkBoxSoda.setGeometry(QtCore.QRect(20, 70, 121, 20))
        self.checkBoxSoda.setObjectName("checkBoxSoda")
        self.checkBoxTea = QtWidgets.QCheckBox(self.groupBoxDrinks)
        self.checkBoxTea.setGeometry(QtCore.QRect(20, 100, 111, 20))
        self.checkBoxTea.setObjectName("checkBoxTea")
        self.checkBoxCoffee = QtWidgets.QCheckBox(self.groupBoxDrinks)
        self.checkBoxCoffee.setGeometry(QtCore.QRect(20, 40, 141, 20))
        self.checkBoxCoffee.setObjectName("checkBoxCoffee")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Menu"))
        self.label_2.setText(_translate("Dialog", "Select your\n"
"IceCream"))
        self.label_3.setText(_translate("Dialog", "Select your drink"))
        self.groupBoxIceCreams.setTitle(_translate("Dialog", "IceCream"))
        self.checkBoxRockyRoad.setText(_translate("Dialog", "Rocky Road $5"))
        self.checkBoxChoclateChips.setText(_translate("Dialog", "Mint Choclate Chips $4"))
        self.checkBoxCookieDough.setText(_translate("Dialog", "Cookie Dough $2"))
        self.checkBoxChoclateAlmond.setText(_translate("Dialog", "Choclate Almond $3"))
        self.groupBoxDrinks.setTitle(_translate("Dialog", "Drink"))
        self.checkBoxSoda.setText(_translate("Dialog", "Soda $3"))
        self.checkBoxTea.setText(_translate("Dialog", "Tea $1"))
        self.checkBoxCoffee.setText(_translate("Dialog", "Coffee $2"))
