# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfigDialog(object):
    def setupUi(self, ConfigDialog):
        ConfigDialog.setObjectName("ConfigDialog")
        ConfigDialog.resize(303, 123)
        self.verticalLayout = QtWidgets.QVBoxLayout(ConfigDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelTimeout = QtWidgets.QLabel(ConfigDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTimeout.sizePolicy().hasHeightForWidth())
        self.labelTimeout.setSizePolicy(sizePolicy)
        self.labelTimeout.setObjectName("labelTimeout")
        self.horizontalLayout.addWidget(self.labelTimeout)
        self.lineEditTimeout = QtWidgets.QLineEdit(ConfigDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditTimeout.sizePolicy().hasHeightForWidth())
        self.lineEditTimeout.setSizePolicy(sizePolicy)
        self.lineEditTimeout.setObjectName("lineEditTimeout")
        self.horizontalLayout.addWidget(self.lineEditTimeout)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelTermination = QtWidgets.QLabel(ConfigDialog)
        self.labelTermination.setObjectName("labelTermination")
        self.horizontalLayout_2.addWidget(self.labelTermination)
        self.comboBoxTerm = QtWidgets.QComboBox(ConfigDialog)
        self.comboBoxTerm.setObjectName("comboBoxTerm")
        self.comboBoxTerm.addItem("")
        self.comboBoxTerm.addItem("")
        self.comboBoxTerm.addItem("")
        self.comboBoxTerm.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBoxTerm)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(ConfigDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ConfigDialog)
        self.buttonBox.accepted.connect(ConfigDialog.accept)
        self.buttonBox.rejected.connect(ConfigDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ConfigDialog)

    def retranslateUi(self, ConfigDialog):
        _translate = QtCore.QCoreApplication.translate
        ConfigDialog.setWindowTitle(_translate("ConfigDialog", "Dialog"))
        self.labelTimeout.setText(_translate("ConfigDialog", "超时: (mSecs)"))
        self.labelTermination.setText(_translate("ConfigDialog", "写入换行符"))
        self.comboBoxTerm.setItemText(0, _translate("ConfigDialog", "\\n"))
        self.comboBoxTerm.setItemText(1, _translate("ConfigDialog", "\\r"))
        self.comboBoxTerm.setItemText(2, _translate("ConfigDialog", "\\n\\r"))
        self.comboBoxTerm.setItemText(3, _translate("ConfigDialog", "\\r\\n"))
