# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connect_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_connect_Dialog(object):
    def setupUi(self, connect_Dialog):
        connect_Dialog.setObjectName("connect_Dialog")
        connect_Dialog.resize(520, 150)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed,
            QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            connect_Dialog.sizePolicy().hasHeightForWidth())
        connect_Dialog.setSizePolicy(sizePolicy)
        connect_Dialog.setMinimumSize(QtCore.QSize(520, 150))
        connect_Dialog.setMaximumSize(QtCore.QSize(520, 150))
        connect_Dialog.setFocusPolicy(QtCore.Qt.NoFocus)
        self.verticalLayout = QtWidgets.QVBoxLayout(connect_Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_res_name = QtWidgets.QLabel(connect_Dialog)
        self.label_res_name.setObjectName("label_res_name")
        self.horizontalLayout.addWidget(self.label_res_name)
        self.lineEdit_VIAS_addr = QtWidgets.QLineEdit(connect_Dialog)
        self.lineEdit_VIAS_addr.setObjectName("lineEdit_VIAS_addr")
        self.horizontalLayout.addWidget(self.lineEdit_VIAS_addr)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(connect_Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(connect_Dialog)
        self.buttonBox.accepted.connect(connect_Dialog.accept)
        self.buttonBox.rejected.connect(connect_Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(connect_Dialog)

    def retranslateUi(self, connect_Dialog):
        _translate = QtCore.QCoreApplication.translate
        connect_Dialog.setWindowTitle(_translate("connect_Dialog", "Connect"))
        self.label_res_name.setText(
            _translate(
                "connect_Dialog",
                "Resouce Name"))
        self.lineEdit_VIAS_addr.setText(
            _translate(
                "connect_Dialog",
                "GPIB0::7::INSTR"))
        self.lineEdit_VIAS_addr.setPlaceholderText(
            _translate("connect_Dialog", "GPIB0::7::INSTR"))
