# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginQWidget(object):
    def setupUi(self, loginQWidget):
        loginQWidget.setObjectName("loginQWidget")
        loginQWidget.resize(500, 400)
        loginQWidget.setMinimumSize(QtCore.QSize(500, 400))
        loginQWidget.setMaximumSize(QtCore.QSize(500, 400))
        loginQWidget.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(loginQWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(loginQWidget)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login_bg_label = QtWidgets.QLabel(self.widget)
        self.login_bg_label.setText("")
        self.login_bg_label.setAlignment(QtCore.Qt.AlignCenter)
        self.login_bg_label.setObjectName("login_bg_label")
        self.horizontalLayout.addWidget(self.login_bg_label)
        self.verticalLayout.addWidget(self.widget)
        self.login_bottom = QtWidgets.QWidget(loginQWidget)
        self.login_bottom.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.login_bottom.setStyleSheet("")
        self.login_bottom.setObjectName("login_bottom")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.login_bottom)
        self.horizontalLayout_2.setContentsMargins(10, 0, 10, 15)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.login_bottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    color: rgb(108, 110, 110);\n"
"}\n"
"QPushButton:hover {\n"
"    color: rgb(38, 122, 60);\n"
"}\n"
"QPushButton: pressed {\n"
"    background-color: transparent;\n"
"}")
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.widget_3 = QtWidgets.QWidget(self.login_bottom)
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setObjectName("gridLayout")
        self.account_cb = QtWidgets.QComboBox(self.widget_3)
        self.account_cb.setMinimumSize(QtCore.QSize(0, 45))
        self.account_cb.setStyleSheet("QComboBox {\n"
"color:  rgb(88, 90, 90);\n"
"border: none;\n"
"font-size: 16px;\n"
"border-bottom: 1px solid lightgray;\n"
"background-color: transparent;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"border-bottom: 1px solid gray;\n"
"}\n"
"QComboBox:focus {\n"
"border-bottom: 1px solid rgb(41, 146, 255);\n"
"}\n"
"QComboBox:drop-down \n"
"{\n"
"    border: 0px; \n"
"    width: 40px;\n"
"    background-color: transparent;\n"
"}\n"
"QComboBox:down-arrow {\n"
"border-image: url(:/login/images/downarrow.png);\n"
"width: 20px;\n"
"height: 30px;\n"
"}\n"
"QComboBox:QAbstractItemView {\n"
"    min-height: 30px;\n"
"}\n"
"QComboBox:QAbstractItemView:Item {\n"
"    color:  rgb(88, 90, 90);\n"
"}")
        self.account_cb.setEditable(True)
        self.account_cb.setObjectName("account_cb")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/login/images/picaqiu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.account_cb.addItem(icon, "")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/login/images/batman.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.account_cb.addItem(icon1, "")
        self.gridLayout.addWidget(self.account_cb, 0, 0, 1, 2)
        self.pwd_le = QtWidgets.QLineEdit(self.widget_3)
        self.pwd_le.setMinimumSize(QtCore.QSize(0, 45))
        self.pwd_le.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pwd_le.setStyleSheet("QLineEdit {\n"
"    font-size: 20px;\n"
"    border: none;\n"
"    border-bottom: 1px solid lightgray;\n"
"    background-color : transparent;\n"
"}\n"
"QLineEdit : hover{\n"
"    border-bottom: 1px solid gray;\n"
"}\n"
"QLineEdit : focus {\n"
"    border-bottom: 1px solid rgb(41, 146, 255);\n"
"}")
        self.pwd_le.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.pwd_le.setClearButtonEnabled(True)
        self.pwd_le.setObjectName("pwd_le")
        self.gridLayout.addWidget(self.pwd_le, 1, 0, 1, 2)
        self.auto_login_checkbox = QtWidgets.QCheckBox(self.widget_3)
        self.auto_login_checkbox.setObjectName("auto_login_checkbox")
        self.gridLayout.addWidget(self.auto_login_checkbox, 2, 0, 1, 1)
        self.remember_pwd_checkbox = QtWidgets.QCheckBox(self.widget_3)
        self.remember_pwd_checkbox.setObjectName("remember_pwd_checkbox")
        self.gridLayout.addWidget(self.remember_pwd_checkbox, 2, 1, 1, 1, QtCore.Qt.AlignRight)
        self.login_btn = QtWidgets.QPushButton(self.widget_3)
        self.login_btn.setEnabled(False)
        self.login_btn.setMinimumSize(QtCore.QSize(0, 50))
        self.login_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(108, 149, 144);\n"
"    border-radius: 8px;\n"
"    color : white;\n"
"    spacing: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(38, 134, 113);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(22, 68, 45);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/login/images/shield.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.login_btn.setIcon(icon2)
        self.login_btn.setIconSize(QtCore.QSize(30, 30))
        self.login_btn.setObjectName("login_btn")
        self.gridLayout.addWidget(self.login_btn, 3, 0, 1, 2)
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.login_bottom)
        self.pushButton_2.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_2.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton_2.setStyleSheet("border: none;\n"
"border-image: url(:/login/images/myQRcode.png);")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 3)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout.addWidget(self.login_bottom)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 3)

        self.retranslateUi(loginQWidget)
        self.pushButton.clicked.connect(loginQWidget.slot_show_register_pan)
        self.pushButton_2.clicked.connect(loginQWidget.slot_open_link)
        self.account_cb.editTextChanged['QString'].connect(loginQWidget.slot_enable_login_btn)
        self.pwd_le.textChanged['QString'].connect(loginQWidget.slot_enable_login_btn)
        self.login_btn.clicked.connect(loginQWidget.slot_check_login)
        self.auto_login_checkbox.clicked['bool'].connect(loginQWidget.slot_auto_login)
        self.remember_pwd_checkbox.clicked['bool'].connect(loginQWidget.slot_rem_pwd)
        QtCore.QMetaObject.connectSlotsByName(loginQWidget)

    def retranslateUi(self, loginQWidget):
        _translate = QtCore.QCoreApplication.translate
        loginQWidget.setWindowTitle(_translate("loginQWidget", "Form"))
        self.pushButton.setText(_translate("loginQWidget", "注册账号"))
        self.account_cb.setItemText(0, _translate("loginQWidget", "12345"))
        self.account_cb.setItemText(1, _translate("loginQWidget", "67890"))
        self.auto_login_checkbox.setText(_translate("loginQWidget", "自动登录"))
        self.remember_pwd_checkbox.setText(_translate("loginQWidget", "记住密码"))
        self.login_btn.setText(_translate("loginQWidget", "安全登录"))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    loginQWidget = QtWidgets.QWidget()
    ui = Ui_loginQWidget()
    ui.setupUi(loginQWidget)
    loginQWidget.show()
    sys.exit(app.exec_())
