# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisterQWidget(object):
    def setupUi(self, RegisterQWidget):
        RegisterQWidget.setObjectName("RegisterQWidget")
        RegisterQWidget.resize(500, 400)
        RegisterQWidget.setMinimumSize(QtCore.QSize(500, 400))
        RegisterQWidget.setMaximumSize(QtCore.QSize(500, 400))
        RegisterQWidget.setStyleSheet("QWidget#RegisterQWidget {\n"
"border-image: url(:/register/images/register_bg3.png);\n"
"}")
        self.main_menu_button = QtWidgets.QPushButton(RegisterQWidget)
        self.main_menu_button.setGeometry(QtCore.QRect(20, 20, 50, 50))
        self.main_menu_button.setStyleSheet("QPushButton {\n"
"    border-radius: 25px;\n"
"    background-color: rgb(11, 38, 32);\n"
"    color: rgb(102, 239, 114);\n"
"    border: 2px solid rgb(14, 52, 39);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 4px double rgb(27, 77, 72);\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: rgb(6, 15, 13);\n"
"    border: 4px double rgb(27, 77, 72);\n"
"}\n"
"")
        self.main_menu_button.setCheckable(True)
        self.main_menu_button.setObjectName("main_menu_button")
        self.exit_menu_button = QtWidgets.QPushButton(RegisterQWidget)
        self.exit_menu_button.setGeometry(QtCore.QRect(20, 90, 50, 50))
        self.exit_menu_button.setStyleSheet("QPushButton {\n"
"    border-radius: 25px;\n"
"    background-color: rgb(11, 38, 32);\n"
"    color: rgb(102, 239, 114);\n"
"    border: 2px solid rgb(14, 52, 39);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 4px double rgb(27, 77, 72);\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: rgb(6, 15, 13);\n"
"    border: 4px double rgb(27, 77, 72);\n"
"}\n"
"")
        self.exit_menu_button.setCheckable(False)
        self.exit_menu_button.setObjectName("exit_menu_button")
        self.reset_menu_button = QtWidgets.QPushButton(RegisterQWidget)
        self.reset_menu_button.setGeometry(QtCore.QRect(90, 70, 50, 50))
        self.reset_menu_button.setStyleSheet("QPushButton {\n"
"    border-radius: 25px;\n"
"    background-color: rgb(11, 38, 32);\n"
"    color: rgb(102, 239, 114);\n"
"    border: 2px solid rgb(14, 52, 39);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 4px double rgb(27, 77, 72);\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: rgb(6, 15, 13);\n"
"    border: 4px double rgb(27, 77, 72);\n"
"}\n"
"")
        self.reset_menu_button.setCheckable(False)
        self.reset_menu_button.setObjectName("reset_menu_button")
        self.about_menu_button = QtWidgets.QPushButton(RegisterQWidget)
        self.about_menu_button.setGeometry(QtCore.QRect(90, 0, 50, 50))
        self.about_menu_button.setStyleSheet("QPushButton {\n"
"    border-radius: 25px;\n"
"    background-color: rgb(11, 38, 32);\n"
"    color: rgb(102, 239, 114);\n"
"    border: 2px solid rgb(14, 52, 39);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 4px double rgb(27, 77, 72);\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: rgb(6, 15, 13);\n"
"    border: 4px double rgb(27, 77, 72);\n"
"}\n"
"")
        self.about_menu_button.setCheckable(False)
        self.about_menu_button.setObjectName("about_menu_button")
        self.layoutWidget = QtWidgets.QWidget(RegisterQWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(180, 170, 282, 211))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setVerticalSpacing(18)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setStyleSheet("color: rgb(172, 255, 234);\n"
"font: 14pt \"Hiragino Sans GB\";")
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.account_le = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.account_le.sizePolicy().hasHeightForWidth())
        self.account_le.setSizePolicy(sizePolicy)
        self.account_le.setMinimumSize(QtCore.QSize(0, 35))
        self.account_le.setStyleSheet("background-color: transparent;\n"
"color: rgb(180, 255, 185);\n"
"border: none;\n"
"border-bottom: 1px solid lightgray;")
        self.account_le.setText("")
        self.account_le.setClearButtonEnabled(True)
        self.account_le.setObjectName("account_le")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.account_le)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setStyleSheet("color: rgb(172, 255, 234);\n"
"font: 14pt \"Hiragino Sans GB\";")
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.password_le = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_le.sizePolicy().hasHeightForWidth())
        self.password_le.setSizePolicy(sizePolicy)
        self.password_le.setMinimumSize(QtCore.QSize(0, 35))
        self.password_le.setStyleSheet("background-color: transparent;\n"
"color: rgb(180, 255, 185);\n"
"border: none;\n"
"border-bottom: 1px solid lightgray;")
        self.password_le.setText("")
        self.password_le.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_le.setClearButtonEnabled(True)
        self.password_le.setObjectName("password_le")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.password_le)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setStyleSheet("color: rgb(172, 255, 234);\n"
"font: 14pt \"Hiragino Sans GB\";")
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.confirm_password_le = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confirm_password_le.sizePolicy().hasHeightForWidth())
        self.confirm_password_le.setSizePolicy(sizePolicy)
        self.confirm_password_le.setMinimumSize(QtCore.QSize(0, 35))
        self.confirm_password_le.setStyleSheet("background-color: transparent;\n"
"color: rgb(180, 255, 185);\n"
"border: none;\n"
"border-bottom: 1px solid lightgray;")
        self.confirm_password_le.setText("")
        self.confirm_password_le.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirm_password_le.setClearButtonEnabled(True)
        self.confirm_password_le.setObjectName("confirm_password_le")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.confirm_password_le)
        self.register_button = QtWidgets.QPushButton(self.layoutWidget)
        self.register_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.register_button.sizePolicy().hasHeightForWidth())
        self.register_button.setSizePolicy(sizePolicy)
        self.register_button.setMinimumSize(QtCore.QSize(280, 50))
        self.register_button.setMaximumSize(QtCore.QSize(280, 50))
        self.register_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.register_button.setAutoFillBackground(False)
        self.register_button.setStyleSheet("QPushButton {\n"
"background-color: rgb(41, 81, 42);\n"
"color: rgb(128, 255, 144);\n"
"border-radius: 10px\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgb(86, 182, 90)\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(54, 111, 56);\n"
"color: rgb(81, 186, 90);\n"
"}\n"
"QPushButton:disabeld {\n"
"color: rgb(94, 156, 109);\n"
"background-color: rgb(97, 122, 109);\n"
"}\n"
"QPushButton:!enabled {\n"
"color: rgb(94, 156, 109);\n"
"background-color: rgb(65, 77, 65);\n"
"}\n"
"")
        self.register_button.setFlat(False)
        self.register_button.setObjectName("register_button")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.register_button)
        self.exit_menu_button.raise_()
        self.reset_menu_button.raise_()
        self.about_menu_button.raise_()
        self.layoutWidget.raise_()
        self.main_menu_button.raise_()

        self.retranslateUi(RegisterQWidget)
        self.main_menu_button.clicked['bool'].connect(RegisterQWidget.slot_show_menu)
        self.about_menu_button.clicked.connect(RegisterQWidget.slot_about)
        self.reset_menu_button.clicked.connect(RegisterQWidget.slot_reset)
        self.exit_menu_button.clicked.connect(RegisterQWidget.slot_exit)
        self.register_button.clicked.connect(RegisterQWidget.slot_register)
        QtCore.QMetaObject.connectSlotsByName(RegisterQWidget)

    def retranslateUi(self, RegisterQWidget):
        _translate = QtCore.QCoreApplication.translate
        RegisterQWidget.setWindowTitle(_translate("RegisterQWidget", "Form"))
        self.main_menu_button.setText(_translate("RegisterQWidget", "菜单"))
        self.exit_menu_button.setText(_translate("RegisterQWidget", "退出"))
        self.reset_menu_button.setText(_translate("RegisterQWidget", "重置"))
        self.about_menu_button.setText(_translate("RegisterQWidget", "关于"))
        self.label.setText(_translate("RegisterQWidget", "账      号:"))
        self.label_2.setText(_translate("RegisterQWidget", "密      码:"))
        self.label_3.setText(_translate("RegisterQWidget", "确认密码:"))
        self.register_button.setText(_translate("RegisterQWidget", "注册"))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegisterQWidget = QtWidgets.QWidget()
    ui = Ui_RegisterQWidget()
    ui.setupUi(RegisterQWidget)
    RegisterQWidget.show()
    sys.exit(app.exec_())
